FROM node:20-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Serve production
FROM node:20-alpine

WORKDIR /usr/src/app
RUN npm install -g serve

COPY --from=build /usr/src/app/build ./build

EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
