version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-contraktflow}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./server
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"

  web:
    build: ./client
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://api:5000
    ports:
      - "3000:3000"

volumes:
  pgdata:
