services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-contraktflow}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d contraktflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./server
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:5000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./client
    depends_on:
      api:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=http://api:5000
    ports:
      - "3000:3000"
    command: sh -c "npm run build && npx serve -s build"

volumes:
  pgdata:
